############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Blog"
pageRef = "/blog"
weight = 2

[[main]]
name = "About"
pageRef = "/about"
weight = 3

[[main]]
name = "Svenja"
pageRef = "authors/svenja-dunger"
weight = 4

[[main]]
name = "René"
pageRef = "/authors/rené-kuhn/"
weight = 5

# footer menu
[[footer]]
name = "Home"
pageRef = "/"
weight = 1

[[footer]]
name = "Blog"
pageRef = "/blog"
weight = 2

[[footer]]
name = "About"
pageRef = "/about"
weight = 3

[[footer]]
name = "Authors"
pageRef = "/authors"
weight = 4

